Repository discoverygarden/islandora_drush_utils, pull requests merged in 2024-05, with the labels that each got.

#25 DDST-58: Added drush command for OAI rebuild
  drush.10.services.yml
  src/Drush/Commands/RebuildOaiEntries.php
Labels: minor

#27 DGI9-504 : Remove Older Derivative Commands
  README.md
  drush.10.services.yml
  src/Drush/Commands/DerivativesGenerator.php
  src/Drush/Commands/MissingDerivatives.php
Labels: major

#28 DGI9-504: Allowing dgi_standardar_derivative_examiner:v2
  composer.json
Labels: patch
